stages:
  - test
  - publish

lint:helm:
  image: registry.gitlab.com/gitlab-org/cluster-integration/helm-install-image/releases/3.7.2-kube-1.21.5-alpine-3.15
  script:
    - helm lint

publish:
  stage: publish
  script:
  - curl --request POST
         --form "token=${CHARTS_TRIGGER_TOKEN}"
         --form ref=master
         --form "variables[CHART_NAME]=${CI_PROJECT_NAME}"
         --form "variables[RELEASE_REF]=${CI_COMMIT_REF_NAME}"
         https://gitlab.com/api/v4/projects/2860651/trigger/pipeline
  rules:
  - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?$/ && $CI_PROJECT_URL == "https://gitlab.com/gitlab-org/charts/gitlab-agent"'
  - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?$/ && $CI_PROJECT_URL == "https://gitlab.com/gitlab-org/security/charts/gitlab-agent"'
