apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gitlab-agent.fullname" . }}
  labels:
    {{- include "gitlab-agent.labels" . | nindent 4 }}
data:
{{- if .Values.config.caCert }}
  ca.crt: {{ .Values.config.caCert | quote }}
{{- end }}
